### ISSUE TITLE
[FEATURE]Merge Mohist, Uranium and Contigo patches

### ISSUE THREAD

**Issue by HowardZHY** [CrucibleMC/Crucible#107]
see title

**Comment by EverNife** [comment]
Can you explain EXACTLY what you want?

"I hant this feature from that project, that feature from the other!"

Just saying "why not mix all of them together?" does not seems to be request...


For example, why no mix Crucible with sponge?

**Comment by HowardZHY** [comment]
configurable things from mohist.yml and other enhancements

**Comment by EverNife** [comment]
> configurable things from mohist.yml and other enhancements

Can you give us an example, one feature that you would like to be on Crucible and why you would like that?

**Comment by HowardZHY** [comment]
# Setting: console_name Default: Server   # Front of the console, for example /say

**Comment by EverNife** [comment]
Nice, now we are achieving something.

Open an issue for that, something like:

"[FEATURE] Make it possible to change the console_name, for example on the command /say"
