### ISSUE TITLE
[FEATURE]1.8+ vanilla client support

### ISSUE THREAD

**Issue by HowardZHY** [CrucibleMC/Crucible#108]
New clients , old game mechanism with most things configurable

**Comment by UeberallGebannt** [comment]
Why would you want this? You wouldn't be able to use mods and can just use Spigot 1.7/1.8 ProtocolHack instead

**Comment by HowardZHY** [comment]
Spigot ProtocolHack is really outdated and KC servers have more things to config than spigot



At 2022-05-31 13:30:46, "UeberallGebannt" ***@***.***> wrote:

Why would you want this? You wouldn't be able to use mods and can just use Spigot 1.7/1.8 ProtocolHack instead

**Comment by juanmuscaria** [comment]
Anything outside forge 1.7.10 is out of scope. Currently, crucible does not support plain vanilla clients (trying to join with a vanilla client will make the server wait for the forge handshake) and there are no plans to support anything that is not plain forge and mods on 1.7.10
If you are using vanilla, which you will need to if you want a multi-version server, there are ***a lot*** of spigot 1.8 forks as well you can use proxies with ViaVersion/ViaBackwards and pretty much any vanilla server jar with bungeecord support.
