### ISSUE TITLE
[BUG] Crash when i add archaicfix (without logs)

### ISSUE THREAD

**Issue by quentin452** [CrucibleMC/Crucible#111]
**Describe the bug**

The server crash when i add archaicfix without logs

How to find archaicfix(https://github.com/embeddedt/ArchaicFix)

**To Reproduce**

1. install archaicfix + dependencies
2. open the server
3. See crash

**Logs**

no logs

**Environment (please complete the following information):**

- Crucible Version: [Crucible-1.7.10-dev-4eab54a-server]
- Plugins:  [no plugins]
- Mods:[00gasstation-mc1.7.10-0.3.0,falsepatternlib-mc1.7.10-0.10.10,archaicfix-mc1.7.10-0.3.0-16-g059b8b4]
- Java Version: [graalvm-ce-java8-21.2.0]
- OS: [EndeavourOS(linux)(idk what version)]

**Comment by quentin452** [comment]
unsupported by archaicfix

**Comment by EverNife** [comment]
Just placing it here in case anyone asks:

https://github.com/embeddedt/ArchaicFix/issues/34
