### ISSUE TITLE
Unable to download libraries

### ISSUE THREAD

**Issue by cqzhcs** [CrucibleMC/Crucible#119]
[cmd.txt](https://github.com/CrucibleMC/Crucible/files/10041830/cmd.txt)

**Comment by LeStegii** [comment]
Can confirm, doesn't work as https://github.com/juanmuscaria/maven/raw/master/ doesn't work anymore.

**Comment by juanmuscaria** [comment]
In this case it's either github limiting people or bad connection, I'll look into possibly making an alternative mirror in case github blocks someone's download.
