### ISSUE TITLE
Malisiscore/Malisisdoors Mod Crashing Server

### ISSUE THREAD

**Issue by RupticMC** [CrucibleMC/Crucible#12]
Malisiscore or Malisisdoors is causing Crucible to crash without any errors. Instantly crashes. 

Malisiscore version: 0.14.3
Malisisdoors version: 1.13.2
Crucible version: v2.0

**Comment by evernife** [comment]
Send us the log files '-'
The entire log!

**Comment by RupticMC** [comment]
Latest.log : https://paste.helpch.at/cenuhiyequ.md
fml-server-latest.log : https://paste.helpch.at/ikutapufuf.coffeescript
fml-junk-earlystartup.log : https://paste.helpch.at/ixoqaresoj.css

**Comment by brunoxkk0** [comment]
Please add `-noverify` on your JVM arguments. On my test server, it works.

malisiscore - 0.14.3
malisisdoors - 1.13.2

**Comment by RupticMC** [comment]
Thank you.
Also, wouldn't that cause some security concerns?

As a suggestion, I would suggest creating a Discord server to see if there is anyone from the community that would help each other.

What are the travertine improvements you guys made with Crucible?

**Comment by juanmuscaria** [comment]
* Also, wouldn't that cause some security concerns?
Only if you were running a webserver or other application, a minecraft server would have no problem.

* As a suggestion, I would suggest creating a Discord server to see if there is anyone from the community that would help each other.
We have plans to do that in the future.

* What are the travertine improvements you guys made with Crucible?
So far none, but this is on our list of plans to fix several mod errors (like thaucmraft desync).

**Comment by evernife** [comment]
For mod fixes, go for 
https://github.com/CrucibleMC/Grimoire-Mixins
