### ISSUE TITLE
[BUG] Build fail

### ISSUE THREAD

**Issue by AlexCatze** [CrucibleMC/Crucible#120]
**Describe the bug**
Crucible build fails
(AFAIK, this happens because of mojang resource download api deprecation, it can be solved by updating to new ForgeGradle GTNH fork)

**To Reproduce**
1. Clone this repo
2. Run "./gradlew setupCrucible"
3. See error

**Expected behavior**
Successfull build.

**Logs**
https://pastebin.com/XtiejzMy

**Environment:**
- Crucible Version: v5.3
- OS/Java Version: Windows 10 with Java 1.8.0_352 and macos-10.15 (Github CI) with Java 8.0.345+1

**Comment by microwin7** [comment]
Fix [\[tree/staging\]](https://github.com/CrucibleMC/Crucible/tree/staging)
Commit: https://github.com/CrucibleMC/Crucible/commit/c1889d224d8222be112668e53c1f77e3b02aed1e
