### ISSUE TITLE
[BUG] [Cauldron] The EntityPlayerMP lose reference when the player dies.

### ISSUE THREAD

**Issue by EverNife** [CrucibleMC/Crucible#121]
The EntityPlayerMP lose reference when the player dies.

On cauldron, it seems the reference to the EntityPlayerMP is not lost on the player's Death, but on Thermos/Crucible it seems to be lost on death. *(this info needs to be checked)*

I just do not know witch one is correct.

I will make more tests to see what happens on pure forge.

Where the reference is lost on Thermos/Crucible
https://github.com/CrucibleMC/Crucible/blob/8df2607c770cb8301be08917263de8e6ceba3f0f/patches/net/minecraft/server/management/ServerConfigurationManager.java.patch#L560

**Comment by EverNife** [comment]
Ok, just checked, the **DEFAULT BEHAVIOR of FORGE** is to lose the reference to the EntityPlayerMP on player Death.

I think Cauldron may have though it was a good idea to not do so, and thermos reverted that back.

**Comment by LeStegii** [comment]
Can confirm that this is forge behaviour. Bukkit doesn't do this though, so some forks may have this implemented into forge.

**Comment by EverNife** [comment]
Well, there is nothing to be fixed related to this matter. 
Mods created focused on Cauldron-Only should be fixed one by one in order to respect the Forge Behavior.
