### ISSUE TITLE
A problem occurred running the server launcher

### ISSUE THREAD

**Issue by XcelOrbit** [CrucibleMC/Crucible#124]
Hello, so I got a basic crucible server setup, however upon adding my modpack to it, the server only outputs a problem occurred running server launcher and it closes the server.

**Comment by juanmuscaria** [comment]
Checkout https://cruciblemc.github.io/docs/crucible/basics/troubleshooting for how to troubleshoot what may be the problem and in case you can't figure out what you need to send for us to help.
