### ISSUE TITLE
Descriptive README.md

### ISSUE THREAD

**Issue by ryleu** [CrucibleMC/Crucible#141]
What is this project actually about? What is a Thermos? Why is this useful? Why would I want to use Crucible?

None of these questions are answered unless you go down a rabbit hole of Crucible > Thermos > KCauldron > Cauldron, which may not even be the correct path. 

I would like to see the readme explain what is going on with Crucible.

**Comment by drori200** [comment]
Crucible is designed for people who want to run plugins and mods together, those people most likely already know about one of the past iterations of crucible (Thermos, Cauldron....) and so there is no need to explain this.

As for advantages there's already info about it

If you think there are any worthy changes then i suggest you make a PR with the changes you want to be made to the README

**Comment by ryleu** [comment]
Mind if I copy & modify what you just sent to make a PR?

**Comment by EverNife** [comment]
> Mind if I copy & modify what you just sent to make a PR?

That would be welcome!

In the worst case we can take what you want to write down and just do small changes on it!

**Comment by ryleu** [comment]
looks like the issue was fixed
