### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zeff9801** [CrucibleMC/Crucible#143]
**Describe the bug**
Server crashed during startup when java 11 is selected and custom-npc mod is installed.

**Logs**
[15:40:16] [main/INFO] [FML]: There was a problem trying to load the mod dir tweaker /home/container/mods/CustomNPC-Plus-1.8.6-nomixin.jar
java.lang.reflect.InaccessibleObjectException: Unable to make field final jdk.internal.loader.URLClassPath jdk.internal.loader.ClassLoaders$AppClassLoader.ucp accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @5a4bef8
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340) ~[?:?]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280) ~[?:?]
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176) ~[?:?]
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170) ~[?:?]

**Environment (please complete the following information):**
- Crucible Version: staging-9edb19ef
- Plugins: AsyncWorldEditInjector@3.5.2, LuckPerms@5.3.3, ChatReaction@1.8.0, AsyncWorldEdit@3.5.4, Essentials@2.13.1, EssentialsProtect@2.13.1, BungeeChatAPI@1.0.1, NametagEdit@4.4.10, Vault@1.7.2-b107, EssentialsSpawn@2.13.1, ProtocolLib@3.6.5, WorldEdit@6.1.2;b3fbe8b, BungeeGuard@1.3-SNAPSHOT, ChatEx@2.7.1, CraftingStore@2.9.1, WorldGuard@6.1, EverNifeCore@2.0.3.4, BetterItemRestrict@1.0.3, Crucible_Server@1.7.10-staging-9edb19ef
- Mods: 1.7.10-staging-9edb19ef, Forge Mod Loader@7.10.99.99, Minecraft Forge@10.13.4.1614, KImagine@0.2, MobiusCore@1.3.8-mapless, FoamFixCore@1.0.4, UniMixins@0.1.15, UniMixins: Mixin (UniMix)@0.1.15, UniMixins: Compatibility@0.1.15, UniMixins: Mixingasm@0.3, UniMixins: SpongeMixins@2.0.1, UniMixins: MixinBooterLegacy@1.2.1, UniMixins: GasStation@0.5.1, UniMixins: GTNHMixins@2.2.0, UniMixins: MixinExtras@0.1.15, Armourer's Workshop@1.7.10-0.48.5, Carpenter's Blocks@3.3.1, CoreTweaks@0.3.3.2, Hodgepodge@2.4.5, CustomNPC+@1.8.6
- Java Version: 11

**Comment by KAMKEEL** [comment]
@zeff9801 Do you have more of the log?

**Comment by drori200** [comment]
@zeff9801 make sure you are using the mixinless version of CNPC, you are using UniMixin which will not work with the normal version of CNPC

**Comment by KAMKEEL** [comment]
He is @drori200 and I thought mixin version works with CNPC+. As long as unimixins is loaded first

**Comment by KAMKEEL** [comment]
I believe it's because of Nashorn. I'll have to fix it

**Comment by zeff9801** [comment]
> @zeff9801 make sure you are using the mixinless version of CNPC, you are using UniMixin which will not work with the normal version of CNPC

It is the mixinless version

**Comment by EverNife** [comment]
Closing this in favor of https://github.com/CrucibleMC/Crucible/issues/148

For now, Teporary solution is to disable the script of customnpcs and use java 21.
