### ISSUE TITLE
[BUG] Crash on start

### ISSUE THREAD

**Issue by smuurf-xyzz** [CrucibleMC/Crucible#145]
**Describe the bug**
Server crashed druing startup with baubles and botania from GTNewHorzons repo. Also many mods from his repo has the same problem.

**Expected behavior**

**Logs**
https://gist.github.com/smuurf-xyzz/5aa0ab9c0d51e2155d439c486ff40bfd

**Environment (please complete the following information):**
- Crucible Version: staging-9edb19ef
- Mods: Baubles-1.0.4, Botania-1.10.9-GTNH
- Java Version: 17
- OS: Windows 10

**Comment by EverNife** [comment]
It seems to be related with  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9568 and https://github.com/GTNewHorizons/Botania/pull/7


As of pureforge the limit should be 
![image](https://github.com/CrucibleMC/Crucible/assets/11357801/dfd3a2c4-dbbd-46f9-a3c0-f679c86a60e8)

Myabe increase on Crucible itself migh solve the issue

**Comment by RehabCZ** [comment]
I encountered this issue multiple times and i can recommend this mod [**Anti Id Conflict**](https://www.curseforge.com/minecraft/mc-mods/anti-id-conflict) that scans and spits out logs with free ids and occupied ids. Later you can use that to reassign ids if config for that mod allows that. 

Hope it helps a bit

**Comment by EverNife** [comment]
As of the links above, it seems GTNH's Botanias checks directly if the mod Hodgepodge  is loaded for it to apply a custom fix for the potion limitation.

@smuurf-xyzz can you try adding the mod **[Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge/releases)**  to your modpack to see if it works?

**Comment by EverNife** [comment]
Also make sure to be running the startup java arguments **[java9args.txt](https://github.com/CrucibleMC/Crucible/blob/staging/java9args.txt)**

**Comment by smuurf-xyzz** [comment]
> Also make sure to be running the startup java arguments **[java9args.txt](https://github.com/CrucibleMC/Crucible/blob/staging/java9args.txt)**

Thanks thats solved issue
