### ISSUE TITLE
[BUG]Unable to launch GTNH 2.6.0

### ISSUE THREAD

**Issue by CrazyNutLz** [CrucibleMC/Crucible#151]
The latest GTNH update, version 2.6.0 stable, has been released, but tests show it cannot run the server using Crucible. 

I saw a similar feedback post on Discord: https://discord.com/channels/682358465175355393/1228738432000327702. My situation is the same as theirs. 

I have already managed to run GTNH 2.6.0 through Crucible following the method in this post. I still hope that the developers can resolve this issue in the new version.
Thanks a lot

**Comment by RealSilverMoon** [comment]
You can temporary fix this and run GTNH2.6.0 by replacing fastutil.jar on libraries\it\unimi\dsi\fastutil. Seems that 8.5.12 works well.

**Comment by juanmuscaria** [comment]
6f59520e491032b2ff01cc6fb153d9a8e4b5299f
