### ISSUE TITLE
[BUG?] Inventory of player clears after first joining to the server (from Thermos)

### ISSUE THREAD

**Issue by ErriourMe** [CrucibleMC/Crucible#158]
I updated my server from Thermos to Crucible. Map and player data was got from old Thermos server. In that time I had something in the inventory.  After starting the core, when I'm joining to the server, my inventory clears. No 

I tryed to compare old and new .dat files and found that Tharmos had symbolic item IDs in the inventory, but Crucible has numeric IDs now. In that reason the core clears invenotry (maybe).

How to fix it?

**To Reproduce**
1. Download and run Thermos core (https://github.com/CyberdyneCC/Thermos/releases/tag/58)
2. Join to the server, place some items in the inventory, leave from server.
3. Change the core to Crucible and run. The world must remain from the Thermos (https://github.com/CrucibleMC/Crucible/releases/tag/staging-0c25d25)
4. Join to the server again

**Environment (please complete the following information):**
- Crucible Version: `1.7.10-staging-0c25d250`
- Plugins (20): `AutoSaveWorld@4.15, PrometheusExporter@2.1.1, WorldEdit@6.0;3342-78f975b9, MaxBans@2.3, OpenInv@2.2.7, Essentials@Pre2.14.1.3, VoxelSniper@5.170.0-SNAPSHOT-jnks317-gitfcb8fe1, iConomy@7.0, PermissionsEx@1.22.6, PlugMan@2.0.2, WorldEditFIX@12.0, Vault@1.5.6-b49, HideStream@3.3, TimingsPatch@0.1, ChatManager@1.19.1, EssentialsSpawn@Pre2.14.1.3, Multiverse-Core@2.5-b691, WorldGuard@5.6.6-SNAPSHOT, Multiverse-Portals@2.5-b699, Crucible_Server@1.7.10-staging-0c25d250`
- Mods (52): `Minecraft Coder Pack@9.05, Crucible Server@1.7.10-staging-0c25d250, Forge Mod Loader@7.10.99.99, Minecraft Forge@10.13.4.1614, KImagine@0.2, CodeChicken Core@1.0.7.47, packetapi@1.3.1, Carpenter's Blocks@3.3.8.1, Chisel@1.5.8.6, Custom Stuff 3@0.7.10, DrZhark's Mo'Creatures Mod@6.3.1, EventHelper@1.7.10-1.11, examplemod@1.0, Extra Doors@1.5.1, Fall@1.0.0, HolyLight Decor Mod@0.0.3, IronFence@1.1.0, Uncle Jeff's Walls Mod@v1.7.10-00.01.05 Beta, KeyAndCodeLock@1.4, mcf_lootpacks@0.13, Core@0.13, mcf_tempbuffs@0.13, mcf_drugs@0.13, mcf_slotmachines@0.13, Clan Mod@1.0.0, MCF S.P.E.C.I.A.L.@0.13, MCF Perks@0.13, Friend Mod@1.0.0, Flags Mode@2.0, MBot Core Mod@1.0.0, syncsafechests@0.13, mcf_phantom_blocks@0.13, mcf_disassemble@0.13, Trade Mod@1.0.0, mcf_clanitems@0.13, mcf_core@0.13, Fallout Mob Mod@1.0, chunk_filter@0.13, Character Customization@0.13, Flan's Mod@0.13, Stacks@1.0, Small Utility Mod@1.0.0, Item Shop Mod@1.0.0, quest_markers@0.13, XlvsEnch@1.0.0, Radiation mod@0.13, CustomNpcs@1.7.10d, mcf_clanbases@0.13, mcf_lootcontainers@0.13, In-game NBTEdit@1.7.2.2, Oceancraft@1.4.1, spark@1.6.4`
- Java Version: `Temurin 1.8.0_402-b06`
- OS: `Debian 12`

**Comment by Richard-Rogalski** [comment]
I migrated just fine from thermos, are you sure both servers are looking at the same .dat files? I had to move some files from using online UUIDs to offline UUIDs

**Comment by ErriourMe** [comment]
> I migrated just fine from thermos, are you sure both servers are looking at the same .dat files? I had to move some files from using online UUIDs to offline UUIDs

Yes, it's the same .dat files. Players UUIDs didn't change (I'm useing custom launcher). Position, storages from CustomNPCs, gamemode -- this info is unchangable when I joined to the server. Only inventory was broken.

**Comment by EverNife** [comment]
@ErriourMe have you found a reason or a logic on this issue?
