### ISSUE TITLE
[BUG]The item-nbt-api-plugin-2.9.2 plug-in error is reported and cannot be used normally

### ISSUE THREAD

**Issue by Kkidult** [CrucibleMC/Crucible#162]
**Describe the bug**
[latest.log](https://github.com/user-attachments/files/16644305/latest.log)

**To Reproduce**
1. Do '...'
3. See error

**Expected behavior**

**Logs**
If applicable, attach your log files and/or crash reports here.

**Screenshots**

**Additional context**

**Environment (please complete the following information):**
- Crucible Version: [e.g. v5.3, dev-<commit hash>]
- Plugins: [paste the output of `/crucible plugins` here, if it's too big please use a paste service]
- Mods: [paste the output of `/crucible mods` here, if it's too big please use a paste service]
- Java Version: [paste the output of `java -version` here]
- OS: [e.g. Windows 10, Ubuntu 20.04.4 LTS]

**Comment by EverNife** [comment]
_The questions on the issue are meanted to be answered '-'_

Anyway, it seems you are using an old version of NBT-API.

The support for Crucible was inserted on NBT-API directly, try updating your NBT-API to the lastest version.
There should be a log like this in your server.

![image](https://github.com/user-attachments/assets/f0f4c5ed-ce88-44c3-8ef8-22a1a739f0b4)

**Comment by Kkidult** [comment]
I'm using 2.9.2 nbtapi, and I can find out on bukkit that the current 1.7.10 version of nbtapi should be 2.9.2.
https://dev.bukkit.org/projects/nbt-api/files

**Comment by Kkidult** [comment]
> 我正在使用 2.9.2 nbtapi，我可以在 bukkit 上发现 nbtapi 的当前 1.7.10 版本应该是 2.9.2。
> https://dev.bukkit.org/projects/nbt-api/files

**Comment by Kkidult** [comment]
> _关于这个问题的问题的回答是“-”_
> 
> 无论如何，您似乎正在使用旧版本的 NBT-API。
> 
> 对 Crucible 的支持直接插入到 NBT-API 上，请尝试将您的 NBT-API 更新到最新版本。您的服务器中应该有这样的日志。
> 
> ![image](https://private-user-images.githubusercontent.com/11357801/358838506-f0f4c5ed-ce88-44c3-8ef8-22a1a739f0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjkxMDUsIm5iZiI6MTcyMzk2ODgwNSwicGF0aCI6Ii8xMTM1NzgwMS8zNTg4Mzg1MDYtZjBmNGM1ZWQtY2U4OC00NGMzLThlZjgtMjJhMWE3MzlmMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzFhYjgwNWY1MDFiYjVkZDNkM2UwYWEyZWE5ODUzNjQ1NDhmMmYyODM2YWFjZWY5MjAxODA2NmY2YTBjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kq6lNKr9wiHFBPeW3OvixCcdes73qnXMemppbYLFbK0)

我正在使用 2.9.2 nbtapi，我可以在 bukkit 上发现 nbtapi 的当前 1.7.10 版本应该是 2.9.2。
https://dev.bukkit.org/projects/nbt-api/files

**Comment by Kkidult** [comment]
> _关于这个问题的问题的回答是“-”_
> 
> 无论如何，您似乎正在使用旧版本的 NBT-API。
> 
> 对 Crucible 的支持直接插入到 NBT-API 上，请尝试将您的 NBT-API 更新到最新版本。您的服务器中应该有这样的日志。
> 
> ![image](https://private-user-images.githubusercontent.com/11357801/358838506-f0f4c5ed-ce88-44c3-8ef8-22a1a739f0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjkxMDUsIm5iZiI6MTcyMzk2ODgwNSwicGF0aCI6Ii8xMTM1NzgwMS8zNTg4Mzg1MDYtZjBmNGM1ZWQtY2U4OC00NGMzLThlZjgtMjJhMWE3MzlmMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzFhYjgwNWY1MDFiYjVkZDNkM2UwYWEyZWE5ODUzNjQ1NDhmMmYyODM2YWFjZWY5MjAxODA2NmY2YTBjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kq6lNKr9wiHFBPeW3OvixCcdes73qnXMemppbYLFbK0)

And using the same nbtapi plugin works fine on the Uranium server in 1.7.10

**Comment by Kkidult** [comment]
> _关于这个问题的问题的回答是“-”_
> 
> 无论如何，您似乎正在使用旧版本的 NBT-API。
> 
> 对 Crucible 的支持直接插入到 NBT-API 上，请尝试将您的 NBT-API 更新到最新版本。您的服务器中应该有这样的日志。
> 
> ![图像](https://private-user-images.githubusercontent.com/11357801/358838506-f0f4c5ed-ce88-44c3-8ef8-22a1a739f0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzAwMTAsIm5iZiI6MTcyMzk2OTcxMCwicGF0aCI6Ii8xMTM1NzgwMS8zNTg4Mzg1MDYtZjBmNGM1ZWQtY2U4OC00NGMzLThlZjgtMjJhMWE3MzlmMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4MjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MTE1YjE0ZTJjOWFkODg3MTBjMDdjMDg0MWFmOGQ2ODI5YjE0MzY1NzMwMWEwNmVjNTE2OGUxYjkwZjIwMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZd3B13OLFyYednWDD0Pzl3zoTiYMrDvemLTqWcl770)

Having the same problem on the thermos server, I have to use the thermos or Crucible server for the needs of the module, if you can fix this problem, it really helps

**Comment by EverNife** [comment]
Test this version here:

https://modrinth.com/plugin/nbtapi/version/2.10.0

**Comment by Kkidult** [comment]
> Test this version here:
> 
> https://modrinth.com/plugin/nbtapi/version/2.10.0

I tested Crucible v5.4 first, there are still some bugs, and then I tested the latest beta release, and it seems that there are no errors, thanks

**Comment by EverNife** [comment]
Thanks, i am glad it worked.

We will be creating a new relase soon.
