### ISSUE TITLE
[BUG]The ForgeMultipart module does not load properly

### ISSUE THREAD

**Issue by Kkidult** [CrucibleMC/Crucible#163]
ForgeMultipart-1.7.10-1.2.0.345-universal is used, and the pre-module is CodeChickenLib-1.7.10-1.1.3.141-universal. You need to put them in the 1.7.10 folder in the mod folder for them to load properly.
It can be used normally on the THERMOS server.
[latest.log](https://github.com/user-attachments/files/16691109/latest.log)
[mods.zip](https://github.com/user-attachments/files/16691120/mods.zip)

**Comment by mts2200** [comment]
You need to use GTNH forks or fix ur version. Not a Crucible issue.

**Comment by Kkidult** [comment]
> You need to use GTNH forks or fix ur version. Not a Crucible issue.

1.7.10 is all old mods, a lot of authors are inactive, you know, I'm just here to try my luck and see if I can solve it through the server

**Comment by mts2200** [comment]
GTNH is active. You can try to use their mod forks and also report this issue. Your mod version is not compatible with the new ASM version. GTNH uses new ASM versions, I think this issue should be solved.

**Comment by Kkidult** [comment]
> GTNH is active. You can try to use their mod forks and also report this issue. Your mod version is not compatible with the new ASM version. GTNH uses new ASM versions, I think this issue should be solved.

It did work, it was successfully loaded using GTNH's mod, there are so many ways you know, I did learn this method, thank you very much

**Comment by EverNife** [comment]
Seems to be resolved :D
