### ISSUE TITLE
[BUG] Applied Energistics incompatibility

### ISSUE THREAD

**Issue by SrYthan** [CrucibleMC/Crucible#164]
**Describe the bug**
Em uma atualização do applied energistics do grupo GTNH da versão 411 para a versão 412, gerou uma incompatibilidade com o crucible, acontece que o sistema de autocraft não funciona no servidor, o botão abaixo
![image](https://github.com/user-attachments/assets/afbfc3b8-27c7-4736-ac24-b7ded148d228)

acaba por não fazer nada sendo assim impossível de avançar para o craft plan, o que me faz ter certeza de que é um problema com o crucible é o fato de que testei no Thermos e funcionou corretamente como na imagem abaixo é mostrado
![image](https://github.com/user-attachments/assets/74ef1787-5d0b-4cc2-ba80-1e0d1dc61553)

o changelog completo das alterações feitas no mod está no link abaixo
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/compare/rv3-beta-408-GTNH...rv3-beta-412-GTNH

**To Reproduce**
1. baixe a ultima versão do crucible server e também a ultima versão ou qualquer uma indo da 412 acima e inicie o servidor
2. crie um sistema básico de crafting no applied e tente solicitar o sistema a fazer algum craft
3. See error

**Expected behavior**
Creio que algo tenha sido alterado na base do forge do crucible ou coisa parecida que possa ter gerado este problema.

**Logs**
If applicable, attach your log files and/or crash reports here.

**Screenshots**

**Additional context**

**Environment (please complete the following information):**
- Crucible Version: latest
- Mods: [appliedenergistics2@rv3-beta-412-GTNH ou qualquer outra acima desta]

**Comment by EverNife** [comment]
Corrigido ao atualizar a biblioteca fastutils em eccfcc875286a2f527f83e28c7c81ae1e7eb7913

Pelos meus testes está funcionando corretamente.
A partir de amanha farei mais testes em um servidor em produção, mas parece estar dentro da normalidade.
