### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by ghost** [CrucibleMC/Crucible#169]
invalid

**Comment by EverNife** [comment]
What? What do you mean by SpyGlass, you meanted this item?

![image](https://github.com/user-attachments/assets/f2526ef2-690f-4902-82a6-4fecd5a4554d)

If yes, this item is not present on 1.7.10
This core is for 1.7.10 '-'

**Comment by ghost** [comment]
Sorry, I went to report an issue from another mod and it lead me here, idk why.
