### ISSUE TITLE
Question Load Chunk on forge tick

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#18]
Load Chunk on forge tick its in cauldron.yml what does it do.
Better for perfroamnce enable or disable

**Comment by spannerman79** [comment]
Disable.  This will create phantom chunk loading if you leave it enabled. 1.7.10 has enough issues with mods that create this issue itself without it being enabled by default....

**Comment by perezzloy** [comment]
Turning off this parameter creates many dupes and glitches with mods such as AE2.

**Comment by evernife** [comment]
@perezzloy are you skiping tiles on?

> tileentities.yml

```
settings:
  skip-tileentity-ticks: true
```
