### ISSUE TITLE
Unable to start server.

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Crucible#22]
Getting this error when trying to start the server on my modpacks update:
```
java.lang.NoClassDefFoundError: org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder
	at org.bukkit.configuration.file.FileConfiguration.<clinit>(FileConfiguration.java:56)
	at net.minecraft.server.MinecraftServer.loadOptions(MinecraftServer.java:2035)
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 15 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at org.objectweb.asm.ClassReader.readShort(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:34)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:108)
	at java.lang.System.exit(System.java:345)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
```

Modlist:

1. [1.7.10]bspkrsCore-universal-6.15.jar
2. Baubles-1.7.10-1.0.1.10.jar
3. CodeChickenLib v1.1.3.140.jar
4. CodingLib-0.2.8b50.jar
5. ForgeMultipart-1.7.10-1.2.0.345-universal.jar
6. ForgeRelocation-1.7.10-0.0.1.4-universal.jar
7. ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
8. MrTJPCore-1.1.0.33-universal.jar
9. CarpentersBlocksCachedResources.zip
10. EJML-core-0.26.jar
11. ABO-MC1.7.10-BC7.1release4.0.10.jar
12. AcademyCraft-1.0.7.jar
13. ActuallyAdditions-1.7.10-r21.jar
14. Advanced Generators v0.9.20.123.jar
15. advancedgenetics-1.7.10-1.5.9.jar
16. ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
17. aether-1.7.10-1.6.jar
18. AFSU-1.2.3a-Freeza.jar
19. AIImprovements-1.7.10-0.0.1b8.jar
20. Ancient Warfare v2.4.115.jar
21. Animation API v1.2.4.jar
22. AoA-Tslat-1.1.3.jar
23. AOBD v2.9.2.jar
24. Applied Energistics 2 rv3-6.jar
25. Aquaculture-1.7.10-1.2.6.21.jar
26. arcane_engineering-0.2.7.jar
27. ArchitectureCraft-1.7.2-mc1.7.10.jar
28. ArsMagica 2 v1.4.0.009.jar
29. AsieLib-1.7.10-0.4.9.jar
30. AttachableGrinder-4.0.0.jar
31. AuraCascade-557.jar
32. Automagy v0.28.2.jar
33. Avaritia-1.13.jar
34. Avaritiaddons-1.4b.jar
35. backpack-2.0.1-1.7.x.jar
36. bdlib v1.9.4.109.jar
37. Better Storage v0.13.1.127.jar
38. BetterAchievements-1.7.10-0.1.0.jar
39. BetterFps-1.0.1.jar.disabled-enable-for-fps-boost-but-disables-signs
40. BiblioCraft[v1.11.7][MC1.7.10].jar
41. BiblioWoods [Highlands] v1.4.jar
42. BiblioWoods [NATURA] v1.5.jar
43. BiblioWoods[BiomesOPlenty][v1.9].jar
44. BiblioWoods[Forestry][v1.7].jar
45. Big Reactors v0.4.3A.jar
46. binnie-mods-1.7.10-2.0.22.7.jar
47. BioCristals-1.7.10-1.8.11.jar
48. BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
49. Blood Magic v1.3.3-17.jar
50. BloodArsenal-1.7.10-1.2-5.jar
51. Blur-MC1.7.10-1.0.1-2.jar
52. Bookshelf-1.7.10-1.0.4.187.jar
53. Born+in+a+Barn+1.7.x.jar
54. Botania r1.8-249.jar
55. Brandons Core v1.0.0.12.jar
56. buildcraft-7.1.23.jar
57. buildcraft-compat-7.1.7.jar
58. Carpenter's Blocks v3.3.8.1.jar
59. Chisel v2.9.5.11.jar
60. Chocolate Quest v1.1d.jar
61. Code Chicken Core v1.0.7.47.jar
62. CoFHCore-[1.7.10]3.1.4-329.jar
63. compacter-1.2.1.15-mc1.7.10.jar
64. CompactSolars-1.7.10-4.4.41.316-universal.jar
65. Computronics-1.7.10-1.6.6.jar
66. CookieCore-1.7.10-1.4.0-11.jar
67. Decocraft-2.4.2_1.7.10.jar
68. denseores-1.6.2.jar
69. DMTweaks-1.0.0.jar
70. Draconic Evolution v1.0.2h.jar
71. DummyCore1.13.jar
72. Enchanting Plus v3.0.2-d.jar
73. Enchiridion+2-1.7.10-2.0.2a.jar
74. Ender Core v0.2.0.39.jar
75. Ender IO v2.3.0.429.jar
76. Ender Storage v1.4.7.38.jar
77. EnderTech-1.7.10-0.3.2.405.jar
78. EternalSingularity-1.7.10-1.0.4.jar
79. EUREKA v3.0.2.jar
80. Extra Cells v2.3.14b197.jar
81. Extra Utilities v1.2.12.jar
82. ExtraTiC-1.7.10-1.4.6.jar
83. Factorization-1.7.10-0.8.109.jar
84. fastcraft-1.25.jar
85. FastLeafDecay-1.7.10-1.4.jar
86. Fluxed Trinkets-1.7.10-1.0.54.jar
87. Forbidden Magic v0.575.jar
88. Forestry v4.2.16.64.jar
89. ForgottenRelics-1.7.3-[Final].jar
90. FoxLib v0.7.0.jar
91. gadomancy-1.7.10-1.0.7.3.jar
92. Galacticraft-Planets-1.7-3.0.12.504.jar
93. GalacticraftCore-1.7-3.0.12.504.jar
94. GalaxySpace-1.2.6+STABLE.jar
95. Gendustry v1.6.4.135.jar
96. gilded-games-util-1.7.10-1.9.jar
97. GraviSuite-1.7.10-2.0.3.jar
98. GravisuitePatcher_1.7.10.jar
99. growthcraft-1.7.10-2.7.2-complete.jar
100. Guide API v1.0.1-29.jar
101. Hardcore Ender Expansion v1.8.6.jar
102. HeartDrop-1.7.10-1.3.2.jar
103. Hexxit Gear v1.2.0.jar
104. Highlands v2.2.3.jar
105. Highlands.Integrator-1.7.10-0.1.0-2-universal.jar
106. HQM-The+Journey-4.4.4.jar
107. IC2NuclearControl-2.4.3a.jar
108. iChunUtil-4.2.3.jar
109. IguanaTinkerTweaks v2.1.6.jar
110. ImmersiveEngineering-0.7.7.jar
111. Immibis Core v59.1.4.jar
112. industrialcraft-2-2.2.828-experimental.jar
113. inventorypets-1.7.10-1.5.2-universal.jar
114. Iron Chest v6.0.62.742.jar
115. itlt-1.7.10-0.0.8.jar
116. journeymap-1.7.10-5.1.4p2-unlimited.jar
117. JustAFewFish-1.4_for_1.7.10.jar
118. LambdaLib-1.2.3.jar
119. legendgear-1.7.10-2.b.2.1.jar
120. Levels-1.7.10-r3.0.1.jar
121. logisticspipes-0.9.3.132.jar
122. Loot Bags v2.0.17.jar
123. Lucky Block v5.1.0.jar
124. Magical Crops v4.0.0-Beta 5.jar
125. magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar
126. magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar
127. magicbees-1.7.10-2.4.4.jar
128. Mantle v0.3.2b.jar
129. Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
130. MCA-1.7.10-5.2.2-universal.jar
131. Mekanism-1.7.10-9.1.1b.jar
132. MekanismGenerators-1.7.10-9.1.1b.jar
133. MekanismTools-1.7.10-9.1.1b.jar
134. Metallurgy-1.7.10-4.0.9.148.jar
135. MetallurgyChisel-1.7.10-1.0.0.11.jar
136. MetallurgyCore-1.7.10-4.0.5.30.jar
137. MFFS-1.7.10-4.0.0b162.jar
138. MFR Compat - Magical Crops v1-2-1.jar
139. MicdoodleCore-1.7-3.0.12.504.jar
140. MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
141. MineTweaker3-1.7.10-3.0.10B.jar
142. MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
143. ModularPowersuits-1.7.10-0.11.1.117.jar
144. MooFluids-1.7.10-1.5.01.19a.jar
145. Natura v2.2.1a2.jar
146. NaturalAbsorption-1.7.10-1.2.1.jar
147. Necromancy-1.7.10a.jar
148. neiaddons-1.12.15.41-mc1.7.10.jar
149. NEIIntegration-MC1.7.10-1.1.2.jar
150. NetherOres-[1.7.10]2.3.2B1-25.jar
151. No More Recipe Conflict v0.3.jar
152. NodalMechanics-1.7-1.0-7.jar
153. Not Enough Items v1.0.5.120.jar
154. NotEnoughIDs-1.4.3.5.jar
155. NotEnoughThaumcraftTabs-1.0.2.jar
156. NOVA-2015-10-09-universal.jar
157. nTweaks.jar
158. Numina-0.4.1.105.jar
159. OpenBlocks-1.7.10-1.6.jar
160. OpenComputers-MC1.7.10-1.7.2.1166-universal.jar
161. OpenModsLib-1.7.10-0.10.jar
162. OpenModularTurrets-1.7.10-2.2.11-245.jar
163. Ore Dictionary Converter v1.6.1.jar
164. orespawn-1.7.10-20.3.zip
165. Origin-1.7.10-8.0.3.jar
166. p455w0rdslib-1.7.10-1.0.4.jar
167. Pam's DesertCraft 1.7.10a.zip
168. Pam's HarvestCraft v1.7.10Lb.jar
169. Pam's Simple Recipes v1.7.10a.jar
170. plantmegapack-4.33-1.7.10-1492.jar
171. Player API v1.4.jar
172. PneumaticCraft-1.7.10-1.12.7-152-universal.jar
173. PortalGun-4.0.0-beta-6-fix-1.jar
174. PortalGunSounds.pak
175. Primitive Mobs v1.0C.jar
176. ProgressiveAutomation-1.7.10-1.6.35.jar
177. Project Red v4.7.0-12.95-Base.jar
178. Project Red v4.7.0-12.95-Compat.jar
179. Project Red v4.7.0-12.95-Fabrication.jar
180. Project Red v4.7.0-12.95-Integration.jar
181. Project Red v4.7.0-12.95-Lighting.jar
182. Project Red v4.7.0-12.95-Mechanical.jar
183. Project Red v4.7.0-12.95-World.jar
184. RadixCore-1.7.10-2.1.3-universal.jar
185. RanchableFluidCows-1.10.2-1.2.0B1.jar
186. RecurrentComplex-0.9.7.1.1-PATCHED.jar
187. Redstone Armory v1.2.0-41.jar
188. RedstoneArsenal-[1.7.10]1.1.2-92.jar
189. Reliquary v1.2.1.483.jar
190. Sanguimancy v1.1.9-29.jar
191. Simply Jetpacks v1.5.3.jar
192. smallboats-1.7.10-10.13.0-16.1.jar
193. Snad-1.7.10-1.6.01.31a.jar
194. Soul Shards TOW v0.1-RC9-7.jar
195. SoundFilters-0.8_for_1.7.X.jar
196. squidless-1.7.10-0.6.1.jar
197. Tainted-Magic-r7.82.jar
198. Talismans2-1.7.10-1.1.6.jar
199. Techguns.beta.1.2_alphatest4.1.jar
200. Technomancy v0.12.5.jar
201. Thaumaturgical+Knowledge-0.1.5.2+-+1.7.10.jar
202. Thaumcraft Inventory Scanner v1.0.11.jar
203. Thaumcraft NEI Plugin v1.7a.jar
204. Thaumcraft NEI v1.3.0.jar
205. Thaumcraft v4.2.3.5.jar
206. Thaumcraft-Botania Exoflame v1.4.jar
207. ThaumcraftGates-1.4.2.jar
208. ThaumcraftMobAspects-1.7.2-2A.jar
209. ThaumicBases-1.3.1710.4.jar
210. thaumicenergistics-1.1.3.0.jar
211. ThaumicExpansion-1.7.10-4.1.3.jar
212. ThaumicExploration-1.7.10-1.1-55.jar
213. thaumichorizons-1.7.10-1.1.9.jar
214. ThaumicInfusion-4.32.jar
215. ThaumicRevelations-1.7.10-v0.1.0.0a.jar
216. ThaumicTinkerer-2.5-1.7.10-542.jar
217. Thermal Smeltery v1.3.1.4.jar
218. ThermalDynamics-[1.7.10]1.2.1-172.jar
219. ThermalExpansion-[1.7.10]4.1.5-248.jar
220. ThermalFoundation-[1.7.10]1.2.6-118.jar
221. ThermalShade-1.7.10-1.0.jar
222. ThermalSingularities-1.7.10-1.2.jar
223. TiCTooltips-mc1.7.10-1.2.5.jar
224. Tinkers' Construct v1.8.8.991.jar
225. Tinkers' Mechworks v0.2.15.106.jar
226. Travellers Gear v1.16.6.jar
227. Treecapitator v2.0.4.jar
228. TSteelworks-1.7.10-1.1.2-20.jar
229. Tube Stuff v59.0.4.jar
230. twilightforest-1.7.10-2.3.8dev.jar
231. Universal Singularities [Version 8]-1.7.10.jar
232. VoltzEngine-1.7.10-1.11.0b473.jar
233. WAILA v1.5.10.jar
234. WailaHarvestability-mc1.7.10-1.1.6.jar
235. WAILAPlugins-MC1.7.10-0.2.0-24.jar
236. WanionLib-1.7.10-1.6.jar
237. WarpTheory-1.7-1.0-24.jar
238. Wawla-1.0.5.120.jar
239. WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b.jar
240. Witchery v0.24.1.jar
241. Witching Gadgets v1.1.10.jar
242. Ztones v2.2.1.jar

**Comment by Zilacon** [comment]
Server logs:
[fml-server-latest.log](https://github.com/CrucibleMC/Crucible/files/4375290/fml-server-latest.log)
[latest.log](https://github.com/CrucibleMC/Crucible/files/4375291/latest.log)

**Comment by juanmuscaria** [comment]
This appears to be some incompatibility with coremods or snake yaml is corrupted. If reinstalling all libraries does not work it's probably a coremod incompatibility.

**Comment by Zilacon** [comment]
I copied/pasted the libraries from an already working server, so i dont think the libraries are an issue.
Any way to pinpoint which mod is causing the problem? As you can see... Theres quite a few XD

**Comment by Zilacon** [comment]
Alright starting with zero mods, same error... Mods officially not the issue.

**Comment by juanmuscaria** [comment]
If mods aren't the problem, probably it's corrupted libraries

**Comment by Zilacon** [comment]
Replaced the jar with a fresh downloaded one, it starts now.
No idea how the server jar got messed up...
