### ISSUE TITLE
Nothing is working...

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Crucible#27]
No items are being merged/stacked.
No entity tracking or activation ranges are being set.
No mob spawn distances are being set.

And im sure many others arent working as well.
On top of this worlds still arent unloading.
And chunks arent unloading...

Is this going to ever get fixed?

**Comment by evernife** [comment]
"Nothing is working..."

if "Nothing is working..." we can wait a little bit more to put anthing to work :D

**Comment by Zilacon** [comment]
When Thermos is a better option in its 3 year old discontinued state then a continuation of its development, you know you dun goofed.

Back to thermos it is then. Im not going to try to reason with children on getting angry over someone reporting issues with their project.

**Comment by evernife** [comment]
You are not reporting an issue, you are demanding a fix.

**Comment by Zilacon** [comment]
Yes, I am, Because i reported the worlds not unloading 2 months ago and that has yet to be addressed. So i put it on here with the rest of the problems. THAT WORKED ON THERMOS

**Comment by Zilacon** [comment]
Worlds still not unloading.
![Screenshot_562](https://user-images.githubusercontent.com/3002248/80316114-c528ca00-87b0-11ea-8e92-9b5d85ef6b8e.png)

**Comment by juanmuscaria** [comment]
What you're using to list your worlds?
