### ISSUE TITLE
When new relese ;}

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#3]
I am waiting. I am waiting.

**Comment by evernife** [comment]
Are you having any issue in your current v2.0 crucible?

https://github.com/CrucibleMC/Crucible/releases/tag/v2.0

**Comment by KubiRem** [comment]
No. Just some food when i eat it it s back after it was eaten

**Comment by evernife** [comment]
Ok, closing it.
There is no estimated time for new release. 
There is only 4 commits ahead the previous release. 

When a new big change is made up or enough commits wore commited, we will draw a new release :D

Check out in a few days/weeks.
