### ISSUE TITLE
essentials causing server crash

### ISSUE THREAD

**Issue by MaxifeuxG** [CrucibleMC/Crucible#32]
**To Reproduce**
Steps to reproduce the crash:
1. Run Server with plugin and mods 1.7.10
2. wait for two players to go to a different place in the world
3. wait a few minutes
4. server close

**Versions (please complete the following information)**
 - Crucible: Crucible-1.7.10-3.1-server.jar
 - Armourers-Workshop Mod: Armourers-Workshop-1.7.10-0.48.3
 - CustomNPCs Mod: CustomNPCs-1.7.10
 - Naruto Anime Mod: Naruto-Anime-Mod-by-Mathioks-1.0
 - GlibysVC Mod: GlibysVC-1.7.10-0.6.2a
 - Plus daliments Mod: Plus daliments-1.7.10 v7
 - SlashBlade Mod: SlashBlade-Mod-mc1.7.10-r88
 - Thirst Mod: Thirst-Mod-1.7.10-1.8.14

**Crash Log**
https://gist.github.com/MaxifeuxG/d324c134e2346cf77ab95e7d46f1852a

**Additional context**
the world is big and has npc of custom npc

**Comment by evernife** [comment]
Is there a crash-report ?

A file tha is inside a folder called `crash-reports`, asside from `mods `folder and `configs `folder.

![image](https://user-images.githubusercontent.com/11357801/82087013-b2c1f200-96c5-11ea-959a-65d50139fefc.png)

**Comment by MaxifeuxG** [comment]
Hello I know where the crash report is located but no crash report is created it is for his that I send the link of the logs

**Comment by evernife** [comment]
Do you have the same issue on a Thermos server?

**Comment by MaxifeuxG** [comment]
no I don't have a problem on Thermos

**Comment by juanmuscaria** [comment]
Are you using essentials?

**Comment by MaxifeuxG** [comment]
yes

**Comment by juanmuscaria** [comment]
Try removing it and see if the issue persists.

**Comment by MaxifeuxG** [comment]
I do a search on google and I was advised this version of essentials
link: https://dev.bukkit.org/projects/essentials/files/891400
I no longer find a bug
