### ISSUE TITLE
Crashing during server start

### ISSUE THREAD

**Issue by Lucasmellof** [CrucibleMC/Crucible#33]
Here is the crash report: https://hastebin.com/jitebiroji

**Comment by Lucasmellof** [comment]
I migrate from Thermos

**Comment by evernife** [comment]
Sure, you can migrate to thermos, thats is always an option!

**Comment by Lucasmellof** [comment]
I have already migrated from thermos. This crash-report was generated by Crucible

**Comment by evernife** [comment]
Sorry for my missunderstanding...

**Comment by evernife** [comment]
Try adding 

jvm argument: -noverify

**Comment by Lucasmellof** [comment]
Worked, Thank u
