### ISSUE TITLE
Why is there so much useless stuff?

### ISSUE THREAD

**Issue by sliva-name** [CrucibleMC/Crucible#37]
Server startup is too long and there are a lot of unnecessary libraries.
I would like to see more performance in the future

**Comment by spannerman79** [comment]
You do understand the framework that cauldron - the base of what previous projects including this one - is based on.  Right?

If you want a faster start up get better hardware and don't expect something to be fast if running on some el chepo Atom based CPU.

**Comment by evernife** [comment]
"Startup is too long", can you give us a comparation?

Can you try to start a modpack with a few different projects like:
-  Thermos
-  Crucible
-  Other fork (like Uranium maybe?)

And check out if is trully taking that much longer?

**Comment by sliva-name** [comment]
take a look uranium ;)

16 окт. 2020 г. 20:48 пользователь "Pétrus Pradella" <
notifications@github.com> написал:

"Startup is too long", can you give us a comparation?

Can you try to start a modpack with a few different projects like:

   - Thermos
   - Crucible
   - Other fork (like Uranium maybe?)

And check out if is trully taking that much longer?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CrucibleMC/Crucible/issues/37#issuecomment-710304136>,
or unsubscribe

**Comment by evernife** [comment]
If you wish to send what i asked, maybe we can take a look at the problem.

> Can you try to start a modpack with a few different projects like:
>...
> And check out if is trully taking that much longer?

Send us the startup-time

**Comment by sliva-name** [comment]
Crucible - 20s
Uranium - 6s

пт, 16 окт. 2020 г., 21:24 Pétrus Pradella <notifications@github.com>:

**Comment by sliva-name** [comment]
Uranium ~ 50mb libraries
Crucible ~ 80mb

пт, 16 окт. 2020 г., 21:27 А С <antyuhov2@gmail.com>:

**Comment by juanmuscaria** [comment]
Crucible is a fork of Thermos, the only libraries changes we have is updated Special Source and added fastutils for a faster chunk map. Thermos has a lot of obscure changes that we have no idea what it does.
Most things we did in this project was fixing common bugs and updating timings to timings v2

**Comment by evernife** [comment]
@sliva-name Can you give me Uranium libs and version you used to test?
I tried to download from their Jenkins

![image](https://user-images.githubusercontent.com/11357801/96296534-cd2a2f80-0fc5-11eb-8e3d-ba878316bfeb.png)

But is not working at all, it does not have some libs inside the libs zip...

![image](https://user-images.githubusercontent.com/11357801/96296600-e8953a80-0fc5-11eb-9f3e-abb02b774430.png)

**Comment by sliva-name** [comment]
Last version

пт, 16 окт. 2020 г., 21:40 Pétrus Pradella <notifications@github.com>:

**Comment by evernife** [comment]
Gona ask again in few words.

I need the jar and libs, the one i downloaded from their their jenkins (latest version) is not working.
Do you have it?

**Comment by GedeonGrays** [comment]
> I need the jar and libs, the one i downloaded from their their jenkins (latest version) is not working.
Hi o/
You probably want #271's library since they only work. So stated on their Jenkins.

**Comment by evernife** [comment]
> > I need the jar and libs, the one i downloaded from their their jenkins (latest version) is not working.
> 
> Hi o/
> You probably want #271's library since they only work. So stated on their Jenkins.

Ty, havent noticed that little note, i will test it now

**Comment by evernife** [comment]
Attempt 1- Uranium - [16:07:44] [Server thread/INFO]: Done (23,345s)! For help, type "help" or "?"
Attemtp 3- Uranium - [16:12:55] [Server thread/INFO]: Done (22,577s)! For help, type "help" or "?"
Attemtp 6- Uranium - [16:16:46] [Server thread/INFO]: Done (24,800s)! For help, type "help" or "?"




Attempt 2- Crucible - [16:09:05] [Server thread/INFO]: Done (18,724s)! For help, type "help" or "?"
Attemtp 4- Crucible - [16:14:09] [Server thread/INFO]: Done (18,382s)! For help, type "help" or "?"
Attemtp 5 - Crucible - [16:15:14] [Server thread/INFO]: Done (18,890s)! For help, type "help" or "?"


With these mods 
![image](https://user-images.githubusercontent.com/11357801/96299911-20eb4780-0fcb-11eb-9a48-fd2f3155c61e.png)

And these plugins
![image](https://user-images.githubusercontent.com/11357801/96299930-2779bf00-0fcb-11eb-9712-6431638ce1ed.png)

**Comment by juanmuscaria** [comment]
I did some tests with my test server and here are the results:
![Screenshot at 16-35-03](https://user-images.githubusercontent.com/34891068/96301728-2191d700-0fe7-11eb-9808-de1e10bcac2d.png)

My plugin and mod list:
![Screenshot at 16-18-42](https://user-images.githubusercontent.com/34891068/96301759-2f475c80-0fe7-11eb-9950-287f05650764.png)

My system:
CPU: Intel Xeon E5-1630v3 (CPU Score 2180)
RAM: 4 GB Hynix DDR4 ECC Server Memory • 2133MHz
SSD: Intel DC S3500 SSD Drives

Uranium is not compatible with my plugin but I was expecting that since I made my plugin only for my server enviroment.

**Comment by evernife** [comment]
To be fair, Uranium wins on a startup without any mod or plugin 👍 

Uranium 1 Without Any Mod/Plugin - [16:57:28] [Server thread/INFO]: Done (4,092s)! For help, type "help" or "?"
Uranium 2 Without Any Mod/Plugin - [16:58:01] [Server thread/INFO]: Done (3,740s)! For help, type "help" or "?"
Uranium 3 Without Any Mod/Plugin - [16:58:31] [Server thread/INFO]: Done (2,726s)! For help, type "help" or "?"

Crucible 4 Without Any Mod/Plugin - [17:00:12] [Server thread/INFO]: Done (4,240s)! For help, type "help" or "?"
Crucible 5 Without Any Mod/Plugin - [17:01:27] [Server thread/INFO]: Done (4,013s)! For help, type "help" or "?"
Crucible 6 Without Any Mod/Plugin - [17:01:56] [Server thread/INFO]: Done (3,220s)! For help, type "help" or "?"

**Comment by sliva-name** [comment]
That's what I'm talking about. Strange, isn't it?

пт, 16 окт. 2020 г., 23:03 Pétrus Pradella <notifications@github.com>:

**Comment by sliva-name** [comment]
Look at the sources of uranium, you will have something to fix and take
from them. I hope that you will abandon the project and actively develop
it. I know someone who knows almost all kernel bugs and how to fix them. Do
you give it to discord?

17 окт. 2020 г. 7:59 пользователь "А С" <antyuhov2@gmail.com> написал:

That's what I'm talking about. Strange, isn't it?

пт, 16 окт. 2020 г., 23:03 Pétrus Pradella <notifications@github.com>:

**Comment by evernife** [comment]
Have you read all comments, we just shown that on few mods/plugins Uranium is faster, but with several mods and plugins, Crucible is faster. ("""faster""", like few seconds only, almost no difference at all)

What do you want us to fix?

(This project is open for PRs, if you have a friend that wants to help, feel free to invite him)
