### ISSUE TITLE
Signing Book & Quill

### ISSUE THREAD

**Issue by KAMKEEL** [CrucibleMC/Crucible#39]
Issue Present in: Thermos, Crucible Code

Works in: Cauldron, KCauldron, UraniumMC

There is an issue in  Thermos that doesn't allow Book & Quills to save when you press **Done** or **Sign** them. A 'fix' was implemented here to try and fix this issue. This fix did fix the issue with pressing **Done** on a Quill and saving the internal contents, however attempting to Sign the book does not work. You can see this GIF below.

https://gyazo.com/54458d83970bff89d01ba04e6295a5aa

**Comment by juanmuscaria** [comment]
Fixed in ea2582fdb4baff9ee3cc7929426a9f44398edc0c.
