### ISSUE TITLE
MobiusCore Incompatibility (wrong references to internal hashed array list)

### ISSUE THREAD

**Issue by Skyere** [CrucibleMC/Crucible#59]

**Comment by GedeonGrays** [comment]
I confirm the problem.
Previously, MobiusCore-Thermos still worked, but now even it is incompatible with Crucible.

**Comment by mjra007** [comment]
Tested with Crucible 5.0 and also couldnt get it to work.

**Comment by juanmuscaria** [comment]
It uses a [hardcoded reference](https://github.com/CyberdyneCC/MobiusCoreTH/blob/54fd3ff2201861738403581bfd7a42c831511a76/src/main/java/mcp/mobius/mobiuscore/asm/transformers/thermos/TransformerWorldThermos.java#L106) for the hashed arraylist, which was changed and then removed from crucible in favor to a better implementation. We will need an updated for that mod

**Comment by GedeonGrays** [comment]
> We will need an updated for that mod

That is, you will do as Thermos did by releasing their version of MobiusCore. Okay, we'll wait. Thanks for your quick response :3

**Comment by sanik** [comment]
> It uses a [hardcoded reference](https://github.com/CyberdyneCC/MobiusCoreTH/blob/54fd3ff2201861738403581bfd7a42c831511a76/src/main/java/mcp/mobius/mobiuscore/asm/transformers/thermos/TransformerWorldThermos.java#L106) for the hashed arraylist, which was changed and then removed from crucible in favor to a better implementation. We will need an updated for that mod

Can you make a patch or custom version of the mod that will work?

**Comment by Fox2Code** [comment]
Well probably the best solution is to create an `thermos.chaud.HashedArrayList` empty class that extend the "better implementation", IMO this is the easiest way to fix this issue.

**Comment by evernife** [comment]
> Well probably the best solution is to create an `thermos.chaud.HashedArrayList` empty class that extend the "better implementation", IMO this is the easiest way to fix this issue.

Seems simple enought :D

**Comment by spannerman79** [comment]
> That is, you will do as Thermos did by releasing their version of MobiusCore. Okay, we'll wait. Thanks for your quick response :3

Not _quite_.

The fix originally was done at my request (cannot provide issue link as the original repo of the person that made the fix is no longer public/removed - author was https://www.reddit.com/user/RoyCurtis/ ) for KCauldron.  The fix that Thermos had was the exact same release as the KCauldron one - just forked from the

**Comment by AlexCatze** [comment]
Fixed version of opis: https://github.com/AlexCatze/Opis/tree/crucible-support

**Comment by juanmuscaria** [comment]
Closing as solved
