### ISSUE TITLE
Kick form server

### ISSUE THREAD

**Issue by xmssss** [CrucibleMC/Crucible#64]
https://www.pastery.net/dmfwdz/

Chestplate with setFlySpeed(func_75092_a) method. Get this stacktrace. Same proble on Thermos, KCualdron not tested.

P.S. player.capabilities.setFlySpeed((float) 0.05); And method on forge source:
![image](https://user-images.githubusercontent.com/9090102/111837294-bdae6a00-8908-11eb-941d-22f317025636.png)

**Comment by juanmuscaria** [comment]
Because that's a client side method, it's not available in the server.

**Comment by xmssss** [comment]
> Because that's a client side method, it's not available in the server.

Omg. What i don't see Side.Client annotation. Omggg. Sorry((

**Comment by juanmuscaria** [comment]
About changing it in the server side you need to do the following:
```java
EntityPlayerMP player = //get the player somewhere
player.capabilities.flySpeed = 0.05f; //set the speed
player.sendPlayerAbilities(); //update the client with the new information
```
