### ISSUE TITLE
Old Thermos bug with EnderIO SagMill

### ISSUE THREAD

**Issue by xmssss** [CrucibleMC/Crucible#65]
https://github.com/CyberdyneCC/Thermos/issues/512
https://github.com/combak/ShatteredWorld/issues/304

Maybe pickup fix from here - https://github.com/MCImaginarium/Thermos/commit/17259522fb102c3958f8be756f5f7ce6edc65ceb

Trouble confirmed in last dev build

**Comment by juanmuscaria** [comment]
Can you test if it was fixed?

**Comment by xmssss** [comment]
Yes, tested and work normally

**Comment by xmssss** [comment]
Yes, tested and work normally, but tested not in Crucible. Testing later

**Comment by xmssss** [comment]
Yep, fix work.
