### ISSUE TITLE
How can i contact the devs? 

### ISSUE THREAD

**Issue by Skkrskkr69** [CrucibleMC/Crucible#7]
Hello,  i have a few questions related to the project,  How can i contact the devs?
Is there an discord?

**Comment by juanmuscaria** [comment]
You can ask the questions right here, or add me on discord juanmuscaria#0001

**Comment by Skkrskkr69** [comment]
I have send you an request on discord,  thanks for the reply

**Comment by evernife** [comment]
https://discordapp.com/invite/jWSTJ4d
