### ISSUE TITLE
Wiki and Issue archive.

### ISSUE THREAD

**Issue by juanmuscaria** [CrucibleMC/Crucible#8]
We will need a wiki with details on how this project works and how to build it and also among other things related to the project.
We will also need an issue archive with issues that have already been fixed or not to keep registered and make it easier to read the source code to know what each fix does.

**Comment by spannerman79** [comment]
Looking at many of the commit comments many of them are not in english - so it would be difficult for someone like me to even attempt to contribute towards keeping up a wiki page keeping track of the changes done - perfect example is https://github.com/CrucibleMC/Grimoire-Mixins/blob/7bf03ecc124d20965b01ad22080fb388ba933e8b/Mixin-Thaumcraft/src/main/java/io/github/crucible/grimoire/mixins/thaumcraft/MixinTileArcaneLampGrowth.java#L14...L16

While Grimoire is not _directly_ part of the main project its considered a useful add-on/feature to enhance Crucible.

**Comment by evernife** [comment]
I will will try to do that. https://github.com/CrucibleMC/Grimoire-Mixins/issues/2
For now, you can check the description of the entire class on the Readme

![image](https://user-images.githubusercontent.com/11357801/76116117-2c53aa80-5fc8-11ea-9fe6-51a0da06c26a.png)

Besides, if you do not want some of these classes to work, just remove its line from inside the mixin configuration that is inside the Grim-Patch jar.

**Comment by spannerman79** [comment]
> Besides, if you do not want some of these classes to work, just remove its line from inside the mixin configuration that is inside the Grim-Patch jar.

Things like this is the **perfect** example of the need for a wiki

**Comment by juanmuscaria** [comment]
https://github.com/CrucibleMC/docs is now a thing, things to be added should be tracked on it's repo now
