### ISSUE TITLE
Dynamp

### ISSUE THREAD

**Issue by ZeGamerc** [CrucibleMC/Crucible#81]
Bonjour,

Dynmap marche pas avec votre fork

**Comment by evernife** [comment]
Nós somos brasileiros, se cada um começar a falar na sua língua materna, isso aqui vai virar programação orientada a google tradutor.

**Comment by Ishida-nyah** [comment]
O Moodle é gay

**Comment by evernife** [comment]
Reopen (correctly) if the problem persist.
