### ISSUE TITLE
AppleCore problem

### ISSUE THREAD

**Issue by mkrtessa** [CrucibleMC/Crucible#85]
Server don't start with error.
Only one mod is installed - AppleCore-mc1.7.10-3.1.1.jar

Full log: https://pastebin.com/raw/vC97XLpK

**Comment by brunoxkk0** [comment]
Same as https://github.com/CrucibleMC/Crucible/issues/15, please add `-noverify` on your JVM arguments.

**Comment by mkrtessa** [comment]
Unfortunately, this did not solve the problem. The same error.

**Comment by juanmuscaria** [comment]
Please make sure you are using -noverify as jvm argument, not application argument, you must put it before the -jar

**Comment by RehabCZ** [comment]
> Unfortunately, this did not solve the problem. The same error.

For me -noverify did not worked at the end of JVM args so try that in case u haven't already.

**Comment by mkrtessa** [comment]
This my start script now `java -Xmx8G -Xms1G -Xmn256M -Dfml.ignorePatchDiscrepancies=true -Dlauncher.noJAnsi=true -noverify -jar IIS_Crucible.jar nogui`
The launch result is now a little different, but it still doesn't work. Log - https://pastebin.com/YrvkTdYC

**Comment by juanmuscaria** [comment]
Seems like apple core doesn't work with thermos itself, probably there's already a fixed version floating around, but I'll keep this open if anyone happens to have it or knows where to find while I try to find a way to fix it on our side

**Comment by juanmuscaria** [comment]
According to squeek502/AppleCore#115 you can also try using an older version (3.0) while this issue is not fixed.

**Comment by RehabCZ** [comment]
I have Infinity Evolved and everything works fine... 
It has Apple Core too i believe, however it's possible that they're still using some older version

**Comment by mkrtessa** [comment]
Thanks for the tips. I confirm 3.0.0 AppleCore work fine with thermos and Crucible. Newer versions of the mod do not work.
