### ISSUE TITLE
FastAsyncWorldEdit compatibility

### ISSUE THREAD

**Issue by EarWarm** [CrucibleMC/Crucible#86]
The problem is not updating the blocks of the players who are loading when interacting with them from the FastAsyncWorldEdit plugin, for example, when using the //set command, that is, after delivering blocks from the //set command, the players see ghost blocks that should have been updated for them. There is no such problem on CraftBukkit and Spigot kernels.

Build FAWE:
https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-bukkit-21.03.26-b67f782-1287-22.3.10.jar

Crucible version v5.2

**Comment by spannerman79** [comment]
Crucible (and its previous forks) are **hybrid** servers.

For Worldedit to work correctly you need **both** the bukkit plugin as well as the forge mod.  This is needed to correctly handle modded blocks.

If FAWE only focus on bukkit/bukkit API then you cannot use it.

See https://github.com/CrucibleMC/Crucible/issues/73 for similar issue.

**Comment by EarWarm** [comment]
It really works, thanks for the help.

**Comment by spannerman79** [comment]
For the sake of search history, what was the actual solution?
>It really works, thanks for the help.

Just stating; that doesn't say what the actual issue was nor how it was fixed.
