### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#9]
Is there anyway U can fix the comapt bettwen Ur server and this mod Tick Dynamic for 1.7.10
https://github.com/wildex999/TickDynamic Kcauldron version

**Comment by evernife** [comment]
Impossible T.T

This mod uses direct reference to many Minecraft and Forge functions/methods, that said, many of them does not even exist anymore on the current version of forge.

This mod's forge version is: "1.7.10-10.13.2.1230"
Crucible forge version is:  "1.7.10-10.13.4.1614"

This mod is too outdated.
The only way to make it "compat" is the mod author updating his mod to forge "1.7.10-10.13.4.1614" and making all his core-changes using Sponge Mixin for example.

**Comment by KubiRem** [comment]
Ok no problem. Thank You!!!
