### ISSUE TITLE
Crash with Galacticraft mod

### ISSUE THREAD

**Issue by Dreeam-qwq** [CrucibleMC/Crucible#91]
Reproduce Step:
1. Add [GalacticraftCore](https://micdoodle8.com/new-builds/GC-1.7/504/GalacticraftCore-1.7-3.0.12.504.jar), [Galacticraft-Planets](https://micdoodle8.com/new-builds/GC-1.7/504/Galacticraft-Planets-1.7-3.0.12.504.jar) and [MicdoodleCore](https://micdoodle8.com/new-builds/GC-1.7/504/MicdoodleCore-1.7-3.0.12.504.jar)
2. Lanuch server
3. Crash and see the error

Version: Crucible-1.7.10-5.3

Crash report&log
`https://gist.github.com/Dreeam-qwq/5a778a3400fe073099152ac819a044e8`
Java: OpenJDK8

**Comment by hardronix122** [comment]
Try to add -noverify argument before -jar in server startup script

**Comment by Dreeam-qwq** [comment]
> Try to add -noverify argument before -jar in server startup script

It works
