### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by Dragon-Account** [CrucibleMC/Crucible#94]
Crucible throws FileNotFoundException at startup, I think you should do a null check

> at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_261]
>         at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_261]
>         at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_261]
>         at com.google.common.io.Files.newReader(Files.java:86) ~[server-1.7.10.jar:?]
>         at net.minecraft.server.management.UserList.func_152679_g(UserList.java:201) ~[om.class:?]
>         at net.minecraft.server.dedicated.DedicatedPlayerList.func_152620_y(DedicatedPlayerList.java:127) [ls.class:?]
>         at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:35) [ls.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:234) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

**Comment by juanmuscaria** [comment]
Full log?

**Comment by Dragon-Account** [comment]
> Full log?
https://drive.google.com/file/d/13MjqdOZvnaNbg7qVXmcg8vEjitJAS2L1/view

**Comment by drori200** [comment]
Could be something due to language of the OS?

**Comment by juanmuscaria** [comment]
That's normal Minecraft behavior, those warnings where already removed in the dev branch

**Comment by Dragon-Account** [comment]
> Could be something due to language of the OS?

I don't know but on other cores this exception doesn't appear
