### ISSUE TITLE
Bukkit bug of issuing items

### ISSUE THREAD

**Issue by EarWarm** [CrucibleMC/Crucible#96]
Hello, I am faced with a problem that makes it impossible to connect the same items together in the inventory, as well as prevents many mods for merchants from correctly accepting items. When an item is issued via the Bukkit API with any NBT modification, for example, changing displayname or lore, it ceases to stack with other items with exactly the same items created using the mod. I have already observed this problem on version 1.6.4, but there some of the kernel developers managed to fix it.

**Comment by drori200** [comment]
That is the normal behavior for bukkit and forge items interacting. You cannot stack forge items with bukkit items

**Comment by juanmuscaria** [comment]
Actually, it's not normal behavior at all!
Cauldron, thermos and possibly other forks for some reason when making an nbt modification via bukkit it keeps an copy of the nbt in the nbt, making a practically different item.
That behavior was removed in the dev builds.

**Comment by drori200** [comment]
I was sure this was normal. well good to know

**Comment by Aizistral** [comment]
> When a bug persists for long enough, people will inevitably start to believe it is a feature

(c) Mojang

**Comment by juanmuscaria** [comment]
Closing it for now since the issue was already fixed in dev.
