### ISSUE TITLE
Crash with tinkersdefense mod

### ISSUE THREAD

**Issue by UeberallGebannt** [CrucibleMC/Crucible#99]
Hello, I'm trying to run the [Evolving Technology Modpack](https://www.curseforge.com/minecraft/modpacks/evolving-technology) on a Crucible server but it seems to crash because of the [tinkersdefense](https://www.curseforge.com/minecraft/mc-mods/compendium/files/2325729) mod (now called Compendium).
I found this old [issue](https://github.com/Lance5057/Tinkers-Compendium/issues/39) saying it is a bug that doesnt happen with an older version of Thermos.

Crash-Report: https://mclo.gs/4CzXDDh
Latest-Log: https://mclo.gs/ltwaXVW

**Comment by UeberallGebannt** [comment]
Line of code this issue leads to: `ClientCommandHandler.instance.func_71560_a(new TD_Commands());`

**Comment by UeberallGebannt** [comment]
So I guess the problem comes down to the mod trying to register a client side command on the server, could be wrong tho, since I'm not a Forge expert.

**Comment by EverNife** [comment]
![image](https://user-images.githubusercontent.com/11357801/153737970-70fdcb44-598c-455f-a0d4-8e6c21d2adfe.png)

Fixed on Grimoire-Mixins, there is a download link at: https://github.com/CrucibleMC/Grimoire-Mixins-1.7.10/releases/tag/latest
